export default function ActDB() {
  const activities = [
    {
      id: 1,
      name: "Minecraft: montando o PC ideal ifdhuidfhguidfg",
      eventDayId: 1,
      eventDay: "Sexta, 22/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 27,
      locationId: 1,
    },
    {
      id: 2,
      name: "Montando o PC ideal",
      eventDayId: 2,
      eventDay: "Sábado, 23/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 0,
      locationId: 1,
    },
    {
      id: 3,
      name: "Minecraft",
      eventDayId: 3,
      eventDay: "Domingo, 24/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 2,
      locationId: 2,
    },
    {
      id: 4,
      name: "Teste",
      eventDayId: 3,
      eventDay: "Domingo, 24/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 2,
      locationId: 3,
    },
    {
      id: 5,
      name: "Minecraft",
      eventDayId: 1,
      eventDay: "Sexta, 22/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 1,
      locationId: 1,
    },
    {
      id: 6,
      name: "Minecraft",
      eventDayId: 2,
      eventDay: "Sábado, 23/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 15,
      locationId: 2,
    },
    {
      id: 7,
      name: "Minecraft",
      eventDayId: 1,
      eventDay: "Sexta, 22/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 1,
      locationId: 2,
    },
    {
      id: 8,
      name: "Minecraft",
      eventDayId: 1,
      eventDay: "Sexta, 22/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 1,
      locationId: 3,
    },
    {
      id: 9,
      name: "Minecraft",
      eventDayId: 1,
      eventDay: "Sexta, 22/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 1,
      locationId: 3,
    },
    {
      id: 10,
      name: "Minecraft",
      eventDay: "Sábado, 22/10",
      startDate: "10:00",
      endDate: "11:00",
      vacancy: 1,
      locationId: 3,
    },
  ];

  return activities;
}
